package LoveLive;

#use nginx;

sub getSongRandom {

	@songs = (
		'A-NO-NE-GA-N-BA-RE!',
		'After school NAVIGATORS',
		'Ai wa Taiyou Ja Nai?',
		'Aishiteru Banzai!',
		'Aki no Anata no Sora Tooku',
		'Anemone heart',
		'Angelic Angel',
		'Arashi no Naka no Koi dakara',
		'Arifureta Kanashimi No Hate',
		'Baby maybe Koi no Button',
		'Beat in Angel',
		'Binetsu Kara Mystery',
		'Blueberry <3 Train',
		'Bokura no LIVE Kimi to no LIFE',
		'Bokura wa Ima no Naka de',
		'Bokutachi wa Hitotsu no Hikari',
		'CheerDay CheerGirl!',
		'COLORFUL VOICE',
		'Composers and Arrangers',
		'Cutie Panther',
		'Dancing stars on me!',
		'Daring!!',
		'Datte Datte Aa Mujou',
		'Diamond Princess no Yuutsu',
		'Donna Toki mo Zutto',
		'Dreamin\' Go! Go!!',
		'Eien Friends',
		'ENDLESS PARADE',
		'Futari Happiness',
		'Future style',
		'Fuyu ga Kureta Yokan',
		'Garasu no Hanazono',
		'Hane wa Shitte Shimatta no?',
		'Happy maker!',
		'HEART to HEART!',
		'Hello, Hoshi o Kazoete',
		'Himitsu to Hanazono',
		'I\'ll smile for yours',
		'Junai Lens',
		'Kaguya no Shiro de Odoritai',
		'Kaku mo Yuubi na Hi to Narite',
		'Kakumei desu ne? Kamisama!',
		'Kimi No Kuse Ni!',
		'KiRa-KiRa Sensation!',
		'Kitto Seishun ga Kikoeru',
		'Kodoku Na Heaven',
		'Kodoku no Kairou',
		'Koi No Shigunaru Rin rin rin!',
		'Koko de Matteru yo',
		'Kokuhaku Biyori, desu!',
		'Korekara',
		'Korekara no Someday',
		'Koremade no Love Live!',
		'Kururin MIRACLE',
		'Listen to my heart!!',
		'LONELIEST BABY',
		'Love marginal',
		'Love Novels',
		'Love wing bell',
		'LOVELESS WORLD',
		'Mahoutsukai Hajimemashita!',
		'Mermaid festa vol.1',
		'Mermaid festa vol.2 ~Passionate~',
		'Mi wa Mu\'sic no Mi',
		'Mogyutto "love" de Sekkin Chuu!',
		'Moshimo Kara Kitto',
		'Mou Hitori Ja Nai yo',
		'MUSEUM de Dou Shitai?',
		'Music S.T.A.R.T!!',
		'Natsu, Owaranai De.',
		'Natsuiro Egao de 1,2,Jump!',
		'Nawatobi',
		'NEURON,NEURON!!',
		'Nightingale Love Song',
		'Niko puri <3 Joshi dou',
		'No brand girls',
		'NO EXIT ORION',
		'Oh,Love&Peace!',
		'Omoide Ijou ni Naritakute',
		'Onaji Hoshi ga Mitai',
		'Otohime Haato de Rabu Kyuuden',
		'Otome Shiki Ren\'ai Juku',
		'Paradise Live',
		'Private Wars',
		'PSYCHIC FIRE',
		'Pure girls project',
		'Puwa Puwa-O!',
		'Ruteshi Kisuki Shiteru',
		'Saitei de Saikou no Paradiso',
		'Sakkaku CROSSROADS',
		'Senkou Resolution',
		'SENTIMENTAL StepS',
		'Shangri-La Shower',
		'Shiawase Iki no SMILING!',
		'Shiranai Love*Oshiete Love',
		'Shocking Party',
		'Shunjou Romantic',
		'Silent tonight',
		'Snow halation',
		'Soldier game',
		'Someday of my life',
		'Song Centers',
		'Sore wa Bokutachi no Kiseki',
		'Soshite Saigo no Peeji ni Wa',
		'Spicaterrible',
		'START:DASH!!',
		'Storm in Lover',
		'Suki desu ga Suki desu ka?',
		'SUNNY DAY SONG',
		'Super LOVE=Super LIVE!',
		'Susume->Tomorrow',
		'Sweet&sweet holiday',
		'Takaramonozu',
		'Trouble Busters',
		'UNBALANCED LOVE',
		'WAO-WAO Powerful day!',
		'Watashitachi wa Mirai no Hana',
		'WILD STARS',
		'Wonder zone',
		'Wonderful Rush',
		'Yume Naki Yume wa Yume ja nai',
		'Yume no Tobira',
		'Yume(star)ONCE AGAIN',
		'Yuujou no Change',
		'Yuuki No Reason',
		'Zurui yo Magnetic today',
		'?<-HEARTBEAT'
	);

	return $songs[int(rand $#songs)];

}

1;
